.\" Copyright (c) 2011 Jean Schurger
.TH GCALCCMD 1 "17 March 2011"
.SH NAME
gcalccmd \- a console calculator
.SH SYNOPSIS
.B gcalccmd

.SH DESCRIPTION
.B gcalccmd
is the console version of
.B gnome-calculator
the calculator of the GNOME desktop environment.

.SH SEE ALSO
.B gnome-calculator
.sp
.LP
