.\" Copyright (c) 1987-2008 - Sun Microsystems, Inc.
.TH GNOME-CALCULATOR 1 "7 August 2013"
.SH NAME
gnome-calculator \- a desktop calculator
.SH SYNOPSIS
.B gnome-calculator
[
.I OPTION
] ...
.SH DESCRIPTION
.B gnome-calculator
is the official calculator of the GNOME desktop environment.
.SH OPTIONS
.TP
.B \-e, \-\-equation
Start gnome-calculator and display the equation following this option.
.TP
.B \-s, \-\-solve
Solve the equation provided following this option.
.TP
.B \-v, \-\-version
Output version information and exit.
.TP
.B \-h, \-?, \-\-help
Prints the command line options.
.SH SEE ALSO
.PD 0
.TP 18
.B gcalccmd
.sp
.LP
