name: gnome-calculator
version: git
summary: GNOME Calculator
description: |
  GNOME Calculator is an application that solves mathematical equations.
  Though it at first appears to be a simple calculator with only basic
  arithmetic operations, you can switch into Advanced, Financial, or
  Programming mode to find a surprising set of capabilities.

  The Advanced calculator supports many operations, including:
  logarithms, factorials, trigonometric and hyperbolic functions,
  modulus division, complex numbers, random number generation, prime
  factorization and unit conversions.

  Financial mode supports several computations, including periodic interest
  rate, present and future value, double declining and straight line
  depreciation, and many others.

  Programming mode supports conversion between common bases (binary, octal,
  decimal, and hexadecimal), boolean algebra, one’s and two’s complementation,
  character to character code conversion, and more.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-calculator:
    interface: dbus
    bus: session
    name: org.gnome.Calculator

apps:
  gnome-calculator:
    command: desktop-launch gnome-calculator
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Calculator.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-calculator

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  gtksourceview:
    after: [desktop-gnome-platform]
    source: https://gitlab.gnome.org/GNOME/gtksourceview.git
    source-type: git
#    source-tag: 4.0.3
    plugin: autotools
    configflags: [--prefix=/usr]
    organize:
      snap/gtksourceview/current/usr: usr
    build-packages:
      - autoconf-archive
      - gettext
      - gobject-introspection
      - gtk-doc-tools
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpeas-dev
      - libxml2-dev
      - libxml2-utils
      - valac

  gnome-calculator:
    after: [gtksourceview]
    source: .
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-calculator/current/usr]
    organize:
      snap/gnome-calculator/current/usr: usr
# overriding vapidir in build-environment doesn't seem to work
    override-build: |
      sed -i.bak -e "s|vapi_dir]|vapi_dir, '--vapidir=$SNAPCRAFT_STAGE/usr/share/vala/vapi']|g" meson.build
      sed -i.bak -e "s|config',|config', '--vapidir=$SNAPCRAFT_STAGE/usr/share/vala/vapi',|g" src/meson.build
      sed -i.bak -e 's|Icon=org.gnome.Calculator$|Icon=${SNAP}/meta/gui/org.gnome.Calculator.svg|g' data/org.gnome.Calculator.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Calculator.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libxml2-dev
      - libsoup2.4-dev
      - libmpc-dev
      - libmpfr-dev
      - valac
      - yelp-tools
  libraries:
    plugin: nil
    stage-packages:
      - libgee-0.8-2
    prime:
      - "-usr/lib/gnome-calculator/libcalculator.a"
      - "-usr/lib/x86_64-linux-gnu/libgee-0.8.so.*"
      - "-usr/share/appdata"
